# Generated by Django 6.0.2 on 2026-02-17 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='From',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=80)),
                ('lastname', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=80)),
                ('date', models.DateField()),
                ('occupation', models.CharField(max_length=80)),
            ],
        ),
    ]
