# Generated by Django 6.0.2 on 2026-02-18 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_application', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='From',
            new_name='Database_From',
        ),
        migrations.RenameField(
            model_name='database_from',
            old_name='lastname',
            new_name='last_name',
        ),
    ]
